services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./clubdata.sql:/docker-entrypoint-initdb.d/clubdata.sql
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
